---
title: "CAMPHIRE Site Map with RHC Regions"
author: "Douglas Fernald"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# libraries 
library(sf)
library(leaflet)
library(crosstalk)
library(htmltools)
library(leaflet.extras)
library(RColorBrewer)

# GET DATA ----
geo_colo_j <- readRDS("~/Documents/R-Projects/CAMPHIRE/monday_maps/geo_colo_j.rds")
hsrs <- readRDS("~/Documents/R-Projects/CAMPHIRE/monday_maps/hsrs.rds")
rhc_regions_geo <- readRDS("~/Documents/R-Projects/CAMPHIRE/monday_maps/rhc_regions_geo.rds")

# PRE-MAP ----
# set label text
labeling_colo <- paste("<strong>",geo_colo_j$practice, "</strong><br>City: ", geo_colo_j$city, "<br>County: ", geo_colo_j$county, "<br>Specialty: ", geo_colo_j$specialty_2) |> lapply(htmltools::HTML)

# practice points palette
pal3 <- colorFactor(
    palette = 'Dark2', #this can be anything from the R Color Brewer package
    domain = geo_colo_j$specialty_2)

# regions polygon palette
factpal_2 <- leaflet::colorFactor(c("#FF4C4C",#1 
                                    "#E9E946", #2
                                    "#ffb3e6", #3
                                    "#b3ccff", #4
                                    "#c6ecd9", #5
                                    "#d1b3ff", #6
                                    "#ffd1b3", #7
                                    "#ffff99", #8
                                    "#ff0066", #9
                                    "#ff9999", #10
                                    "#ff4dd2", #11
                                    "#ffa31a", #12
                                    "#8c1aff", #13
                                    "#b3ffff", #14
                                    "#b3b3ff", #15
                                    "#66ff99", #16
                                    "#e5e5cc", #17
                                    "#c6538c", #18
                                    "#00e6e6", #19
                                    "#ffdd99", #20
                                    "#4d94ff"), #21 
                                  hsrs$REGION.FACTOR)

# Make the shared data set for filter checkbox to function
sd <- SharedData$new(data = geo_colo_j)


```

``` {r map, echo = FALSE}
# create map layers
leaflet(rhc_regions_geo, height=700, width=900) |>  
    addProviderTiles("CartoDB.Positron") |> 
    addPolygons(fill= F,
                color = "grey",
                weight = 1,
                layerId = ~COUNTYNS) |> 
    addPolygons(data = hsrs,
                fillColor = ~factpal_2(REGION),
                fillOpacity = .1,
                color = "grey",
                weight = 3,
                layerId = ~HS_REGION,
                label = ~ paste("RHC region ",REGION),
                labelOptions = labelOptions(noHide = F, direction = "top", 
                                            textOnly = T,
                                            style = list(
                                                "color" = "dimgrey",
                                                "font-weight" = "bold",
                                                "font-size" = "11px",
                                                "font-style" = "italic",
                                                "border-color" = "rgba(0,0,0,0)"
                                            ))) |> 
    addCircleMarkers(data = sd,
                     label = ~ labeling_colo,
                     radius = 6.5,
                     fillColor = ~pal3(specialty_2),
                     fillOpacity = .70, #some transparency for overlap
                     stroke = T,
                     color ="#FFFFFF",
                     weight = .5,
                     opacity = .75,
                     popup = ~ paste(practice,"<br>City: ", city, "<br>County: ", county)
    ) |> 
    addLegend(data = sd,
              "bottomleft", 
              pal = pal3, 
              values = ~specialty_2,
              title = "Specialty",
              opacity = .8
    ) |> 
    addProviderTiles("CartoDB.Positron") |> 
    leaflet.extras::addResetMapButton() |> 
    crosstalk::bscols(
        widths = c(1,0,5),
        "",
        filter_checkbox(
            id = "specialty_2",
            label = "Select to filter sites...",
            sharedData = sd,
            group = ~specialty_2,
            inline = TRUE),
        ""
    )

```
